### ISSUE TITLE
ResponsiveContainer does not respond to resizing from large to small

### ISSUE THREAD

**Issue by marchaos** [recharts/recharts#172]
ResponsiveContainer computes the size of the chart based on the current window size. It also seems to respond when you make the browser window larger, however if you make the browser window smaller, the chart stays large. Tested on chrome.

**Comment by xile611** [comment]
@marchaos It works fine in [this demo](http://jsfiddle.net/znqLLdev/1/?utm_source=website&utm_medium=embed&utm_campaign=znqLLdev). Can you show your question in an online jsfiddle demo ?

**Comment by marchaos** [comment]
hi Xile. You're correct that it does rescale. I believe the problem I'm having is that I have a chart inside a flexbox container. Since recharts is using javascript to compute the resize, I don't think that it will work with flexbox. This isn't necessarily a recharts issue (or d3.js), but I would presume that a change or config on the recharts side would be needed to achieve what I'm doing.

**Comment by xile611** [comment]
@marchaos Recharts listens to the resize event of the container node. As long as you add a  `ResponsiveContainer` in to a container node,  and the container node can change size when the browser becomes larger or smaller, then the chart will change responsively. So I think it may be the bug of the layout which wrapper the ResponsiveContainer. It will be helpful to show your case in a jsfiddle demo.

**Comment by marchaos** [comment]
@xile611 http://jsfiddle.net/9tjsb7k2/embedded/result/. You'll see it opens to the correct size of the window, and if you resize from a small window to make it larger, it works, but not going from larger to smaller.

**Comment by xile611** [comment]
@marchaos It seems to be the problem of calculation strategy of flex box. You can check this [stackoverflow question](http://stackoverflow.com/questions/7985021/css-flexbox-issue-why-is-the-width-of-my-flexchildren-affected-by-their-content) fro detail.

**Comment by marchaos** [comment]
http://jsfiddle.net/oezx3kh2/embedded/result/

Thanks, adding width: 0 to the children fixed that issue!

**Comment by mrwillis** [comment]
Does anyone know the fix for flexDirection: 'column'? Apparently setting `width : 0` does not fix the issue here.

**Comment by mrwillis** [comment]
I figured it out. Kind of. If you're trying to use `flexDirection: 'column'` and run into this issue, I suggest that on your `ResponsiveContainer` that you add `width={'99%'}` along with a static height, like `height={200}`. This will make the chart resize properly. Just setting `width: 0` on the parent element will not work because for some reason `flex: 1` will not override `width: 0` on the parent element. I have no idea why. According to this blog post, [http://gedd.ski/post/the-difference-between-width-and-flex-basis/](url), it should, but it doesn't.

**Comment by viztor** [comment]
This problem seems to persist.

**Comment by gennaroanesi** [comment]
got it working with a 99% width and a fixed height

**Comment by akuji1993** [comment]
We also got it working using 99% width.

**Comment by nicholasmaddren** [comment]
Working with 99% however it would be nice if this worked at 100%. I'll do some further investigating to understand how this could be resolved in a way that doesn't include hacks.

**Comment by domix90** [comment]
Issue is still there. 

                        `<div className="wrapper" >
				<Header>
				</Header>
				<ResponsiveContainer width={'99%'} height={200}>
					{/* Separated component */}
					<LineChartV portals={this.state.portals} />
				</ResponsiveContainer>
				<div className="timelineDiv">
                                        {/* another component */}
					<TimelineView
						notifications={this.state.notifications}
					/>
				</div>
				<Footer className="footer_container">
					<div className="footer">
						<p style={{ textAlign: 'center' }}>&copy;Footer TEXT</p>
					</div>
				</Footer>
			</div>`

**Comment by tmercado** [comment]
@domix90 I set the height/width of a parent div using percents rather than flex grow. then set the responsive grid height/width props with percents as well. Seemed to work well.

```javascript
<div style={{ height: '1000px', width: '1000px' }} >
    <div style={{ height: '100%', width: '60%' }}>
          <ResponsiveContainer height={/*some percent*/} width={/*some percent*/}>
          </ResponsiveContainer>
     </div>
</div>
```

**Comment by domix90** [comment]
Thanks @tmercado ! 

I decided to switch to Charts.js to avoid this issue for future projects.

**Comment by wouterds** [comment]
Why is this issue closed if it's still an issue and clearly a bug?

**Comment by mixail-novikov** [comment]
I fixed it up using old lifehack with padding.

```
<div style={{position: 'relative', width: '100%', paddingBottom: '250px'}}>
  <div
    style={{
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      top: 0,
    }}
  >
    <ResponsiveContainer>
      <YourChartGoesHere />
    </ResponsiveContainer>
  </div>
</div>
```

paddingBottom value can be in px for fixed height, and in percents for aspect ratio.

**Comment by olelivalife** [comment]
Animations are very slow with width 99%

**Comment by akuji1993** [comment]
@olelivalife You can try to delay or debounce the resize action and only then adjust the size of the container. That means though, that you might have to set the width manually using a ref. 

http://bencentra.com/code/2015/02/27/optimizing-window-resize.html

**Comment by G07cha** [comment]
For me, setting `overflow: hidden` in parent component solves the problem.

```jsx
<div style={{ overflow: 'hidden', 'flex-basis': "50%" }}>
  <ResponsiveContainer>
    <YourChartGoesHere />
  </ResponsiveContainer>
</div>
```

**Comment by vitaliyzh** [comment]
new hack for issue
set `position: relstive` for `.recharts-surface`
```
.recharts-surface {
  position: absolute !important;
  left: 0px;
  top: 0;
}
```

**Comment by bmitchinson** [comment]
> .recharts-surface {
>   position: absolute !important;
>   left: 0px;
>   top: 0;
> }
@vitaliyzh 
`relative`? or `absolute`. Your snippet shows aboslute?

**Comment by ShamansCoding** [comment]
The issue is still there. I have a problem with the flex layout with direction "row". Screen rotation on mobile devices does not resize chart from bigger to smaller height. My solution is to use height equals 94% on ResponsiveContainer so resizing is triggered and animation is not to slow.

It will be great if any fix of this problem will come out.

**Comment by christiaanwesterbeek** [comment]
> Animations are very slow with width 99%

Yep, I had that too. But then I tried the solution right before your comment; the [one](#issuecomment-523362671) by @mixail-novikov. It works flawlessly.

**Comment by reifnotreef** [comment]
Having issues with this as well. Tried everything mentioned here, and in other issues and SO threads.  

The best I was able to do was use a width of 94% to speed up the animation, it's extremely clunky looking while resizing though.
```
    <div style={{ width: ''100%' }}>
      <ResponsiveContainer width="94%" height={450} debounce={1}>
        <BarChart
          data={chartData}
          margin={{
            top: 30,
            right: 0,
            left: 20,
            bottom: 30,
          }}
        >
...
    </div>
```

If I go any lower than 94% the bars get really out of whack in terms of being centered with the parent, using a left margin 20 and no right margin allows them to at least appear centered.

**Comment by christiaanwesterbeek** [comment]
@reifnotreef Let us know if the [one](#issuecomment-523362671) by @mixail-novikov works for you. It is working for me flawlessly.

**Comment by reifnotreef** [comment]
@christiaanwesterbeek it does not. I thought it might have to do with me having a div above my responsize container.
```
    <div className={classes.barGraphWrapper}>
      <div className={classes.header}>
        {title && <div className={classes.headerStyles}>{title}</div>}
        {CustomTitle && <CustomTitle />}
      </div>
      <ResponsiveContainer width="94%" height={450} debounce={1}>
        <BarChart
          data={chartData}
          margin={{
            top: 30,
            right: 0,
            left: 20,
            bottom: 30,
          }}
        >
```
I tried removing the extra header div that but it still didn't work. It causes the bar graph to be rendered at about 25% width instead of 100%.

Either way this issue should not be closed as this is not a "fix" it's a hack/workaround for an inherit problem with the ResponsiveContainer.

**Comment by raj-altrio** [comment]
This should definitely not be closed. Changing the height of the container does not trigger a change in height for the chart.

**Comment by DrLazer** [comment]
> I fixed it up using old lifehack with padding.
> 
> ```
> <div style={{position: 'relative', width: '100%', paddingBottom: '250px'}}>
>   <div
>     style={{
>       position: 'absolute',
>       left: 0,
>       right: 0,
>       bottom: 0,
>       top: 0,
>     }}
>   >
>     <ResponsiveContainer>
>       <YourChartGoesHere />
>     </ResponsiveContainer>
>   </div>
> </div>
> ```
> 
> paddingBottom value can be in px for fixed height, and in percents for aspect ratio.

I can confirm this fix works.
This is a real stinker of a bug from recharts.  I was very close to ditching the library entirely

**Comment by JakeRuth** [comment]
Bumping this, I've been trying to fix this for 4 hours, none of the solutions works for me.

I have a complicated graph where a user can select inputs that cause the number of items in the Legend to grow over time.

So, some of these "fixes" (hacks around a bug) work if the graph legend is static after render.  However once items are added over time this issue comes back.

I am very very close to moving over to Charts.js since they seem to care about stuff like this?

Question to maintainers from a nice dev: Please, please, at least recognize this is a terrible bug.  This is not fixed.  I am on latest 2.0.6 and still seeing this.  It's plaguing my app and my users.  This is not acceptable.

I'd be more than happy to try to put up a PR to fix if someone can point me to the source.  I'll follow up if I find a true fix that actually works for complicated dynamic graphs for rich applications.

**Comment by andrewgarrison** [comment]
I pulled my hair out trying to get the `<ResponsiveContainer/>` to work with my HTML structure, but nothing from this thread or suggestions from elsewhere seemed to work. I instead ditched the responsive container completely and wrote my own hook to resize the chart based on the parent element's width. 

The hook:

```
import { useLayoutEffect, useState, RefObject } from 'react';

export const useElementSize = <T extends HTMLElement>(
  elementRef: RefObject<T>
): number[] => {
  const [size, setSize] = useState<number[]>([0, 0]);

  useLayoutEffect(() => {
    if (elementRef.current) {
      const updateSize = (): void => {
        setSize([
          elementRef?.current?.clientWidth || 0,
          elementRef?.current?.clientHeight || 0,
        ]);
      };
      window.addEventListener('resize', updateSize);
      updateSize();
      return () => window.removeEventListener('resize', updateSize);
    }
  }, [elementRef]);

  return size;
};
```

Implementation:

```
export const Chart = () => {
  const chartData = [{...}];
  const containerRef = useRef<HTMLDivElement>(null);
  const [width, height] = useElementSize(containerRef);

  return (
    <div ref={containerRef} style={{ width: "100%", overflow: "hidden" }}> // overflow: hidden is important
      <LineChart
        height={500}
        width={width} // set the chart width to the width value returned from the hook
        data={chartData}
        margin={{
          top: 5,
          right: 30,
          left: 20,
          bottom: 5,
        }}
      >
        <CartesianGrid strokeDasharray='3 3' />
        <XAxis dataKey='key' />
        <YAxis />
        <Tooltip />
        <Legend />
        <Line
          type='monotone'
          dataKey='otherKey'
          stroke='#2563eb'
          activeDot={{ r: 8 }}
        />
      </LineChart>
    </div>
  );
}
```

Hope this can help others who need their chart to be responsive!

**Comment by FelixRe0** [comment]
+1 Setting the width to 99% is not acceptable...

**Comment by SourOatMilk** [comment]
Wrapping your `useEffect` code in `setTimeout` should do the trick. But honestly, this should be fixed.

**Comment by trent-boyd** [comment]
> new hack for issue
> set `position: relstive` for `.recharts-surface`
> 
> ```
> .recharts-surface {
>   position: absolute !important;
>   left: 0px;
>   top: 0;
> }
> ```

I had a similar fix, but I'm not sure why it works.

```
.recharts-wrapper {
  position: absolute !important;
}
```

**Comment by 8byr0** [comment]
Just to share another hack based on https://github.com/recharts/recharts/issues/1767#issuecomment-598607012 

(99% did not work for me, animation was really slow when resizing parent)

```tsx
import React from "react";
import { ResponsiveContainer } from "recharts";

interface MyChartProps {}

export const MyChart: React.FC<MyChartProps> =
  () => {
    return (
      <div
        sx={{
          width: "100%",
          height: "500px", // or whatever height you want OFC
          overflow: "hidden",
          position: "relative",
        }}
      >
        <div
          style={{
            width: "100%",
            height: "100%",
            position: "absolute",
            top: 0,
            left: 0,
          }}
        >
          <ResponsiveContainer width="100%" height="100%">
            {/* Chart content */}
          </ResponsiveContainer>
        </div>
      </div>
    );
  };
```

**Comment by jarodsim** [comment]
> 

this is sad, i have the same problem

**Comment by mattyvp** [comment]
If resizing the window clips the final x-axis tick text for you, I found creating a custom tick component and setting a negative margin on the final tick solved the issue. In my case I only want the start and end tick to appear, and `interval="preserveStartEnd"` on the `XAxis` was not working.

```typescript
import React, { FC, ReactElement } from 'react'

const MainChartTick: FC<{
  payload?: { value: string; index: number }
  x?: number
  y?: number
  totalItems: number // prop equal to data.length - didn't see a total item count with incoming props
}> = ({ payload, totalItems, x, y }): ReactElement | null => {
  if (!payload || !x || !y) return null
  const { index, value } = payload
  if (!index || index === totalItems - 1) {
    return (
      <g transform={`translate(${x},${y})`}>
        <text x={!index ? 0 : -40} y={20}>
          {value}
        </text>
      </g>
    )
  }
  return null
}

export default MainChartTick
```

**Comment by socramm9** [comment]
My Recommendation is just to stop using `ResponsiveContainer` and just use `AutoSizer` from `react-virtualized-auto-sizer` worked like a Charm for me at least

```
import AutoSizer from "react-virtualized-auto-sizer";

export default function Chart() {
  return (
    <AutoSizer>
      {({ width, height }) => <LineChart width={width} height={height}>{...}</LineChart>}
    </AutoSizer>
  );
}
```

**Comment by monsieurnebo** [comment]
Same issue over here.

**Comment by subwaymatch** [comment]
> My Recommendation is just to stop using `ResponsiveContainer` and just use `AutoSizer` from `react-virtualized-auto-sizer` worked like a Charm for me at least
> 
> ```
> import AutoSizer from "react-virtualized-auto-sizer";
> 
> export default function Chart() {
>   return (
>     <AutoSizer>
>       {({ width, height }) => <LineChart width={width} height={height}>{...}</LineChart>}
>     </AutoSizer>
>   );
> }
> ```

This has finally fixed it for me after hours of trials and errors. Thank you @socramm9 ! 🙏

**Comment by yayidg22** [comment]
> My Recommendation is just to stop using `ResponsiveContainer` and just use `AutoSizer` from `react-virtualized-auto-sizer` worked like a Charm for me at least
> 
> ```
> import AutoSizer from "react-virtualized-auto-sizer";
> 
> export default function Chart() {
>   return (
>     <AutoSizer>
>       {({ width, height }) => <LineChart width={width} height={height}>{...}</LineChart>}
>     </AutoSizer>
>   );
> }
> ```

Works fine

**Comment by mohamed-tayeh** [comment]
Still an issue and will be considering this issue when choosing chart libraries in the future. It's an issue that make dev's spend an unproportionate amount of time on something small

**Comment by Eldenhor** [comment]
I tried all the options that were suggested here, ended up with this solution that worked for me in my React project, silly but works:
`  const [width, setWidth] = useState(99);
  useLayoutEffect(() => {
    setWidth(100);
  }, []);
<ResponsiveContainer width={`${width}%`} height="100%">
  // ...
</ResponsiveContainer>
`

**Comment by suchibharani** [comment]
> I fixed it up using old lifehack with padding.
> 
> ```
> <div style={{position: 'relative', width: '100%', paddingBottom: '250px'}}>
>   <div
>     style={{
>       position: 'absolute',
>       left: 0,
>       right: 0,
>       bottom: 0,
>       top: 0,
>     }}
>   >
>     <ResponsiveContainer>
>       <YourChartGoesHere />
>     </ResponsiveContainer>
>   </div>
> </div>
> ```
> 
> paddingBottom value can be in px for fixed height, and in percents for aspect ratio.

it worked for me

**Comment by gs96222** [comment]
This one worked for me, I was trying to use it inside the MUI Accordian. But this trick working fine on all the 3 major browsers - safari, chrome,firefox

<div style={{display: "flex"}}>
    <div  style={{ flex: 1, width: 0, height: 500 }}>
        <ResponsiveContainer>
            <RechartsAnyChart />
        </ResponsiveContainer>
     </div>
  </div>

**Comment by hiteshlimbanidev** [comment]
this chart is good but still have responsive issue please some one solve this

**Comment by ckifer** [comment]
Hi all, 

I re-opened this issue after recently becoming a maintainer of recharts and am trying to squash these bugs that are recurring issues for a lot of people. 

This thread is long and from what I can tell there are a lot of differences in the code since this issue was originally cut.
The original issue statement:
>however if you make the browser window smaller, the chart stays large.
is no longer true from what I can tell as of the latest version (2.4.0) - [codesandbox](https://codesandbox.io/s/area-chart-in-responsive-container-forked-mns9ty?file=/src/App.tsx

Can those that have commented on this issue chime in about what the current gripes are with `ResponsiveContainer`? As well as if any specific issues in this thread have been fixed? This will help me decide on next steps. Thanks!

**Comment by ckifer** [comment]
I haven't seen any answers suggesting the use of min-width: 0, but if you specify `min-width: 0` on your flex children then this issue is resolved. (see commented out code in CSS file of above repro)

That being said I'll probably make the same change internally so it works by default

**Comment by ckifer** [comment]
Merged #3391 - this defaults min-width to 0 which overrides the default auto value. The original problem with not-shrinking when responsive container is a flex child should be solved. 

Will be released in next patch or minor release. Closing this issue back up. Thanks all!

**Comment by SamuelPrigent** [comment]
> My Recommendation is just to stop using `ResponsiveContainer` and just use `AutoSizer` from `react-virtualized-auto-sizer` worked like a Charm for me at least
> 
> ```
> import AutoSizer from "react-virtualized-auto-sizer";
> 
> export default function Chart() {
>   return (
>     <AutoSizer>
>       {({ width, height }) => <LineChart width={width} height={height}>{...}</LineChart>}
>     </AutoSizer>
>   );
> }
> ```

THANKS !! 🙏🏻

**Comment by Kimbohlovette** [comment]
> 

Many thanks to you @SamuelPrigent  it worked very well for me too

**Comment by NikolyCover** [comment]
Just changing from props of ResponsiveContainer  from width="100%" height="70%" to width="99%" height="70%" worked for me

**Comment by mayurwankhade96** [comment]
issue is still there

my code is like

```
<div
          style={{
            display: "flex",
            flexDirection: "column",
          }}
        >
          <h6>
            Some text
          </h6>
          <div style={{ flexGrow: 1 }}>
               <ResponsiveContainer>
                      // chart here
              </ResponsiveContainer>
          </div>
        </div>
```

its not resizing and with width 99.9 and height 99.8 %, animation is very very slow

**Comment by nikolasrieble** [comment]
@ckifer It seems this is not fully solved. I also just stumbled into this again. 🤔

**Comment by ckifer** [comment]
Yeah I mean we're really just wrapping one of those solutions anyways right with resize detector. 

Most other chart solutions are just responsive out of the box iirc. While we could tell people to go use something else for responsive needs I think that downgrades the out of the box value recharts currently gives (even if this bug exists). 

Personally think we should keep responsive behavior but remove the extra component and have it as a part of each chart. If we need to change the internal implementation to get this to work that should be fine

**Comment by nikolasrieble** [comment]
(1) Our ResponsiveContainer wraps https://www.npmjs.com/package/react-resize-detector
Our way of usage is not the recommended way. We could upgrade the dependency and refactor to align with best practice. This could be a good first step either way. 

(2) In the README it says: 
> Container queries now work in [all major browsers](https://caniuse.com/css-container-queries). It's very likely you can resolve your problem using [pure CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries).

**Comment by ckifer** [comment]
1. Sounds good
2. If we could get a css solution to work internally that would be huge - since container queries are like media queries I'm not sure how it replaces things but i guess investigation needed.

**Comment by DarrenBaldwin07** [comment]
Any updates on this? Would really love a fix

**Comment by ckifer** [comment]
Responsive container has been refactored to use resize detector directly. That will be in the next minor release, but I haven't confirmed if that fixes this or not. Will check

**Comment by ckifer** [comment]
@HHongSeungWoo do you know if your changes fix this?

**Comment by HHongSeungWoo** [comment]
@ckifer No, I think some changes might be needed for size detection in flexbox.
I'll create a PR, could you review it to see if there are any issues?

**Comment by ckifer** [comment]
Yep

**Comment by max-petrenko** [comment]
At v. 2.9, I was able to fix the no-shrink behaviour with the `width='99%'` hack, but charts with flex-basis assignd to them ignored it after the resize. 

However, with v. 2.10.3 of the library, I stopped experiencing the no-shrink behaviour, even in flexbox scenarios, so I highly recommend pulling the latest version to see whether the issue goes away. All my charts are rendered like this, if it matters:
`
<div
          className={cx(
            'chartCard p-6 gap-6 grow-[1] max-w-full',
            conf.type === 'bar' ? 'basis-[37%]' : 'basis-[57%]',
          )}
>
<div className='h-[250px] overflow-x-auto'>
  <ResponsiveContainer debounce={2} width='100%' height='100%' minWidth={%depends on chart type%}>
    <Chart ... />
  </ResponsiveContainer>
</div>
</div>
`

**Comment by phoenixeliot** [comment]
Here's what ended up working for me, with two graphs at about 50% height each in a column. I needed the `flex-grow` for it to grow, and the `overflow: hidden` for it to shrink.
```jsx
<div
  style={{
    height: "95vh",
    display: "flex",
    flexDirection: "column",
  }}
>
  ...other content
  <div
    style={{
      flexGrow: 1,
      display: "flex",
      flexDirection: "column",
      overflowY: "hidden",
    }}
  >
    <div style={{ overflow: "hidden", flexBasis: "50%" }}>
      <ResponsiveContainer width="100%" height="100%">
        ...AreaChart
      </ResponsiveContainer>
    </div>
    <div style={{ overflow: "hidden", flexBasis: "50%" }}>
      <ResponsiveContainer>
        ...AreaChart
      </ResponsiveContainer>
    </div>
  </div>
</div>
```

**Comment by heinsenberg82** [comment]
In my case, `ResponsiveContainer` was inside a `ChartContainer`, and the `ChartContainer` had a fixed `height` and `width` set to 100%. I removed the `width` property on `ChartContainer`  and set `min-width: 100%`, then it worked 🤷‍♂️

**Comment by ckifer** [comment]
ChartContainer is not a recharts component. Where is that coming from @heinsenberg82?

**Comment by heinsenberg82** [comment]
> ChartContainer is not a recharts component. Where is that coming from @heinsenberg82?

`ChartContainer` is a component from shadcn charts. You can see some examples on their website here: https://ui.shadcn.com/charts. They use recharts under the hood.

**Comment by Lueton** [comment]
> > ChartContainer is not a recharts component. Where is that coming from @heinsenberg82?
> 
> `ChartContainer` is a component from shadcn charts. You can see some examples on their website here: https://ui.shadcn.com/charts. They use recharts under the hood.

@heinsenberg82 I did run into the same problem with shadcn charts. I did a little workaround which might help you. I added a parent container and tracked its width with [`react-resize-detector`](https://www.npmjs.com/package/react-resize-detector). The could below should give you an idea on how to do it. 

```jsx

const { height, width, ref } = useResizeDetector<any>({
    refreshRate: 500,
    refreshMode: "debounce",
  });

<div ref={ref} className="w-full h-full">
        <ChartContainer
          config={chartConfig}
          style={{ height: height || 1, width: width || 1 }}
        >
        { /* ... */ }
        </ChartContainer>
</div>
```

**Comment by TechyChan** [comment]
to anyone still facing this annoying issue, please use `display: grid` on the parent container. Example in TailwindCSS:

```
<div className="h-[400px] grid grid-cols-1">
  <ResponsiveContainer width="100%" height="100%">
    <AreaChart ...
  </ResponsiveContainer>
</div>
```

**Comment by PavelVanecek** [comment]
Hi everyone 👋 I am trying to reproduce this issue but cannot. Is there anything we can do better in the responsive container?

**Comment by PavelVanecek** [comment]
Okay I think I found
