### ISSUE TITLE
History dependency

### ISSUE THREAD

**Issue by bkniffler** [recharts/recharts#29]
I don't know why, but history keeps getting installed in recharts/node_modules folder, even though its only defined as a devdependency. Any ideas why? Am I the only one affected by this?

**Comment by xile611** [comment]
I did an experiment and found no problem. Do you depend on `react-router` or any other packages which define history as a peerDependency?

**Comment by bkniffler** [comment]
Its really strange, it is not noted in the installation log, but it still appears in the node_modules folder. I've already cleared the cache, completely removed it, reinstalled it.

```
recharts@0.6.3 node_modules/recharts
├── ima.js-babel6-polyfill@0.1.0
├── classnames@2.2.3
├── oui-dom-utils@0.3.5
├── recharts-scale@0.1.8
├── invariant@2.2.0 (loose-envify@1.1.0)
├── d3-scale@0.4.0 (d3-color@0.3.4, d3-time@0.1.1, d3-time-format@0.2.1, d3-interpolate@0.3.0, d3-format@0.4.2, d3-array@0.6.2)
├── d3-shape@0.4.0 (d3-path@0.1.4)
├── react-smooth@0.0.9 (pure-render-decorator@0.2.0, raf@3.1.0)
├── lodash@4.5.0
└── core-js@2.0.3
```


![ohne titel](https://cloud.githubusercontent.com/assets/4349324/13104733/3def3dba-d55f-11e5-91c7-f8f6669eb8a2.jpg)

**Comment by bkniffler** [comment]
I've investigated it further, check out http://registry.npmjs.org/recharts/-/recharts-0.6.3.tgz 

It includes history module. See here for more infos on this issue
https://github.com/npm/npm/issues/9642

NPM2 seems to fix it, or use the workaround of @othiym23
 
```
I can totally see how that would be confusing. A way to work around this for redux-react-router would be to add a postversion script that runs npm prune --prod, which will strip out devDependencies as long as you publish right after versioning. (Using prepublish here is tricky because that will uninstall devDependencies right after installling them.)

should the fix go in fstream-npm or util/lib/tar.js or both?
It should go in fstream-npm, which will fix it in util/lib/tar.js when we pull down the updated dependency.
```

**Comment by xile611** [comment]
So that's it. My local npm version is 3.3.12, so no problem.

**Comment by bkniffler** [comment]
Hmm.. strange. As far as I understood npm2 should have this fixed, but please look at the tarball
http://registry.npmjs.org/recharts/-/recharts-0.6.3.tgz

History module is still part of your published package, so there is a problem.

**Comment by bkniffler** [comment]
You need to update npm to >= 3.4.0 and then publish a new version. Maybe you could also bump oneuijs to 0.3.6 in that release: https://github.com/recharts/recharts/issues/31

That should fix it.

**Comment by xile611** [comment]
Thanks! I will fix these problems soon.

**Comment by xile611** [comment]
It seems that the bug was resolved in npm2, but not properly fixed for npm3.

See the issue of react-router-redux:
[react-router-redux issue](https://github.com/reactjs/react-router-redux/issues/133)

**Comment by bkniffler** [comment]
For npm3 it is fixed with 3.4.0

Here is a quote:
```
There are two ways for avoiding this issue
- Use the npm versions which is fixed the issue(>=2.4.10 || >3.4.0)
- Remove node_modules/history before publishing the package
```

**Comment by xile611** [comment]
I have try v3.4.0 and v3.7.3, the bug happened again.
So I checked the file [utils/tar](https://github.com/npm/npm/blob/v3.7.3/lib/utils/tar.js#L75) in all the 3.x versions. Then I find that the bug wasn't fixed in any 3.x version.

So I submitted a [issue](https://github.com/npm/npm/issues/11582).
Hope fixed soon.

**Comment by arcthur** [comment]
I fix the release script, and fix the history pack problem. We will publish next version to remove the package.

**Comment by nancyagrwal** [comment]
I'm trying to create Scatter plots using React and Recharts. But i keep on getting the following build error at various places in file, and nothing shows:

**Uncaught SyntaxError: Unexpected token (**
at:
"use strict";
function(series) {
  var n = series.length, o = new Array(n);
  while (--n >= 0) o[n] = n;
  return o;
}
and other places.

What am I doing wrong?
