### ISSUE TITLE
label doesn't work in Reference Data

### ISSUE THREAD

**Issue by MrOxMasTer** [recharts/recharts#3684]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts/issues/new?assignees=&labels=&projects=&template=----please-use-recharts-issue-helper---.md](https://github.com/recharts/recharts/issues/new?assignees=&labels=&projects=&template=----please-use-recharts-issue-helper---.md)

### Steps to reproduce
не нужно

### What is expected?
that the signature will appear near the point

### What is actually happening?
Error

| Environment | Info |
|---|---|
| Recharts | v2.7.2 |
| React | "react": "^18.2.0", |
| System | Windows 11 |
| Browser | Chrome |

![image](https://github.com/recharts/recharts/assets/59291123/65f267e6-cea0-49c1-96f3-42ee3b63984a)
![image](https://github.com/recharts/recharts/assets/59291123/8e9c29c3-0488-436b-bdf9-6f81ddd79f55)

**Comment by ckifer** [comment]
Interesting, `Label` is a valid child of reference dot. For now you can use the `label` prop

https://recharts.org/en-US/api/ReferenceDot#label

**Comment by ckifer** [comment]
Could you reproduce using a sandbox? Seems to be working 
https://codesandbox.io/s/simple-bar-chart-forked-4c7s77?file=/src/App.tsx

**Comment by MrOxMasTer** [comment]
> Interesting, `Label` is a valid child of reference dot. For now you can use the `label` prop
> 
> https://recharts.org/en-US/api/ReferenceDot#label

my label doesn't work at all. Not with the help of props, not with the help of children

**Comment by ckifer** [comment]
Can you reproduce? I can't reproduce the issue so I'm not sure how to help

**Comment by MrOxMasTer** [comment]
> Can you reproduce? I can't reproduce the issue so I'm not sure how to help

I do not know how to show you better. Maybe there is some kind of library conflict going on? I can throw you the code or throw off the list of libraries. Right now I'll try to test it in codebox

**Comment by MrOxMasTer** [comment]
I do not know why, but everything works for me in codebox too https://codesandbox.io/s/simple-bar-chart-forked-rdyg7c?file=/src/App.tsx

**Comment by MrOxMasTer** [comment]
my list of libraries:

"dependencies": {
        "@radix-ui/react-progress": "^1.0.3",
        "@radix-ui/react-select": "^1.2.2",
        "@radix-ui/react-slider": "^1.1.2",
        "@radix-ui/react-slot": "^1.0.2",
        "@tanstack/react-query": "^4.32.0",
        "@types/node": "^20.4.2",
        "@types/react": "^18.2.15",
        "@types/react-dom": "^18.2.7",
        "axios": "^1.4.0",
        "class-variance-authority": "^0.7.0",
        "clsx": "^2.0.0",
        "eslint": "^8.45.0",
        "eslint-config-next": "^13.4.11",
        "global": "^4.4.0",
        "lucide-react": "^0.263.0",
        "next": "^13.4.11",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-hook-form": "^7.45.2",
        "react-select": "^5.7.4",
        "recharts": "^2.7.2",
        "sharp": "^0.32.4",
        "tailwind-merge": "^1.14.0",
        "tailwindcss-animate": "^1.0.6",
        "ts-pattern": "^5.0.4",
        "typescript": "^5.1.6",
        "zod": "^3.21.4",
        "zustand": "^4.3.9"
    },
    "devDependencies": {
        "@typescript-eslint/eslint-plugin": "^6.1.0",
        "@typescript-eslint/parser": "^6.1.0",
        "autoprefixer": "^10.4.14",
        "dotenv": "^16.3.1",
        "eslint-config-airbnb": "^19.0.4",
        "eslint-config-airbnb-typescript": "^17.1.0",
        "eslint-config-prettier": "^8.8.0",
        "eslint-import-resolver-typescript": "^3.5.5",
        "eslint-plugin-import": "^2.27.5",
        "eslint-plugin-jsx-a11y": "^6.7.1",
        "eslint-plugin-n": "^16.0.1",
        "eslint-plugin-prettier": "^5.0.0",
        "eslint-plugin-promise": "^6.1.1",
        "eslint-plugin-react": "^7.33.0",
        "eslint-plugin-react-hooks": "^4.6.0",
        "eslint-plugin-tailwindcss": "^3.13.0",
        "eslint-plugin-unused-imports": "^3.0.0",
        "npm-run-all": "^4.1.5",
        "postcss": "^8.4.27",
        "postcss-styled-syntax": "^0.4.0",
        "prettier": "^3.0.0",
        "prettier-plugin-tailwindcss": "^0.4.1",
        "stylelint": "^15.10.2",
        "stylelint-config-clean-order": "^5.0.1",
        "stylelint-config-standard": "^34.0.0",
        "stylelint-config-standard-scss": "^10.0.0",
        "stylelint-declaration-block-no-ignored-properties": "^2.7.0",
        "stylelint-order": "^6.0.3",
        "stylelint-prettier": "^4.0.0",
        "tailwindcss": "^3.3.3",
        "tailwindcss-debug-screens": "^2.2.1"
    }

**Comment by MrOxMasTer** [comment]
And another question is this. Does refenct dot have any delay? It's just weird. The graph has not been drawn yet and the animation has not been played yet, and the dot is already flying in the sky on the graph

**Comment by ckifer** [comment]
It's probably a next specific issue

**Comment by ckifer** [comment]
I don't remember for sure (on mobile currently) but I don't think they referenced elements have any animation and therefore will appear before at the same time in the overall chart animation starts

**Comment by MrOxMasTer** [comment]
> It's probably a next specific issue

that is, because I use next.js? Will my problem be solved in the future?

**Comment by ckifer** [comment]
> because I use next.js

correct

> Will my problem be solved in the future?

Probably, but the world of Next.js and what it is doing to the React ecosystem is very confusing at the moment. I don't use Next have very little context into how it works. It seems like we need to support it specifically which is quite a pain, but I don't really know how to as I don't know why things are breaking like they are with it.

I take you are using the new Next.js "app" folder?

Can you try adding a `use client;` to the top of your page that uses recharts?

**Comment by MrOxMasTer** [comment]
> > because I use next.js
> 
> correct
> 
> > Will my problem be solved in the future?
> 
> Probably, but the world of Next.js and what it is doing to the React ecosystem is very confusing at the moment. I don't use Next have very little context into how it works. It seems like we need to support it specifically which is quite a pain, but I don't really know how to as I don't know why things are breaking like they are with it.
> 
> I take you are using the new Next.js "app" folder?
> 
> Can you try adding a `use client;` to the top of your page that uses recharts?

Yes, I use the "app" directory. I already had a 'use client' to use the hook and put a delay, otherwise I don't like that the dot appears before the animation of the graph is played
![image](https://github.com/recharts/recharts/assets/59291123/e02fa03f-031b-400f-b33b-9192faa5fe21)

**Comment by ckifer** [comment]
Looks like reduce-css-calc is what is breaking in the `Text` component

here somewhere - still not sure why
https://github.com/recharts/recharts/blob/master/src/component/Text.tsx#L226-L236

**Comment by ckifer** [comment]
@MrOxMasTer do you have `"type": "module"` in your package.json by chance?

**Comment by MrOxMasTer** [comment]
> 
you are absolutely right. I have it in package.json

**Comment by MrOxMasTer** [comment]
![image](https://github.com/recharts/recharts/assets/59291123/af9db600-e569-4c3b-aa9b-7ead23267d80)

**Comment by MrOxMasTer** [comment]
> @MrOxMasTer do you have `"type": "module"` in your package.json by chance?
> 
> Pretty sure its because reduce-css-calc has a default export and ESM doesn't like that https://github.com/MoOx/reduce-css-calc/blob/master/src/index.js#L9

What do I need to do? Remove the type from package.json altogether? Or should I wait for patch updates?

**Comment by ckifer** [comment]
Not totally sure but type module is forcing the use of ESM in your project. That is all well and good but that library doesn't quite support ESM yet and doesn't look like it's had any recent changes. 

Ideally I could refactor to remove that lib but idk how invoked that is yet

**Comment by ckifer** [comment]
@MrOxMasTer reduce css calc was removed in 2.9, could you check if your issue still exists?

**Comment by MrOxMasTer** [comment]
> @MrOxMasTer reduce css calc was removed in 2.9, could you check if your issue still exists?

Updated to a new version. Yes, the Label has appeared, but there are also problems here. The problem with styling using tailwind. with the usual I don't know, but tailwind doesn't work on Label. And maybe I don't understand something, but the position is wrong in my opinion. I set it to be on top, and as a result, the Label is on the bottom

![image](https://github.com/recharts/recharts/assets/59291123/6cb5de1c-7fbc-4889-a90b-d5621d218ac2)

![image](https://github.com/recharts/recharts/assets/59291123/89059933-6882-4380-8437-aab376a53e33)

**Comment by MrOxMasTer** [comment]
![image](https://github.com/recharts/recharts/assets/59291123/79aea0e5-54b6-4e3e-807a-68085efe9ea3)
![image](https://github.com/recharts/recharts/assets/59291123/4e2972cb-f9b8-45ac-9e15-5ba12ac5ea62)

Except font-* styles, does not want anything

**Comment by ckifer** [comment]
charts wasn't made with tailwind in mind so no idea how they work together. 

There is a simple explanation for why the labels appear where they do. 

https://recharts.org/en-US/api/Label 

On that page there is a diagram - imagine the rectangle there is instead just a dot and the text is constrained to the edges of the dot. This makes the displays act how you see here

**Comment by MrOxMasTer** [comment]
> charts wasn't made with tailwind in mind so no idea how they work together.
> 
> There is a simple explanation for why the labels appear where they do.
> 
> https://recharts.org/en-US/api/Label
> 
> On that page there is a diagram - imagine the rectangle there is instead just a dot and the text is constrained to the edges of the dot. This makes the displays act how you see here

Well, how do I style it then? It's kind of cool that you can put a label now, but it's pointless without css styles. I tried all kinds of styles and nothing helped

**Comment by ckifer** [comment]
Since the components are svgs and html css and SVG css are not one to one not everything from tailwind (or any css) will apply. 

See this article for what applies when working with SVG

https://css-tricks.com/svg-properties-and-css/

**Comment by ckifer** [comment]
The color property doesn't apply to SVG, you'll have to use stroke and fill

https://stackoverflow.com/a/17467501

**Comment by MrOxMasTer** [comment]
> Свойство color не применяется к SVG, вам придется использовать обводку и заливку
> 
> https://stackoverflow.com/a/17467501

Okay, I get it. Apply to svg styles. But such a question. And then how do I make an outline around the text or background it?
![image](https://github.com/recharts/recharts/assets/59291123/30c08671-8484-4e6f-b73f-65baf3883b96)

Here is an example of this:

![image](https://github.com/recharts/recharts/assets/59291123/b398c8b7-e345-4134-b363-47c9efb493f6)

**Comment by ckifer** [comment]
I'm not sure we have the elements in place to support that right now, but you can create a custom label that does this. I'm not at the computer right now but I can post an example later

**Comment by MrOxMasTer** [comment]
> I'm not sure we have the elements in place to support that right now, but you can create a custom label that does this. I'm not at the computer right now but I can post an example later

Well, I expect

**Comment by ckifer** [comment]
Closing this since reduceCssCalc has been removed from recharts
