### ISSUE TITLE
XAxis tick not in domain are showing on the sides as well

### ISSUE THREAD

**Issue by anshika1422** [recharts/recharts#3847]
Hi Team when i am trying to implememt highlight and zoom in the code , so the domain sets correctly based on the selected area but the extra ticks are shown visible on the sides as shown below. 
Is there a way to resolve this issue ? Why the ticks not in domain visible?
<img width="1097" alt="image" src="https://github.com/recharts/recharts/assets/46922316/eb0a185f-d6ce-418b-9bae-93a3b17d6327">

**Comment by ckifer** [comment]
Can you give a codesandbox? I've never seen this behavior before

**Comment by ckifer** [comment]
this is weird. if you remove `scale="linear"` the issue goes away, I would let the auto scale do its thing in this case. Otherwise, this is a bug with the difference between `auto` scale and `linear` scale as `linear` should be returned in this case anyways when `auto` is used.

**Comment by anshika1422** [comment]
In our use case we need  all the data points to be visible on xaxis  without skipping any values thats the reason we are using linear scale.  Is there any possible workaround for this ?

**Comment by anshika1422** [comment]
<XAxis
            padding={{ left: 7, right: 7 }}
            dataKey="index"
            type="number"
            domain={[state.left, state.right]}
            allowDataOverflow
            //scale="linear"
            tickCount={10000}
            interval={0}
            tick={
              <XaxisTicks
                dayTicks={false}
                data={data.kpiData}
                dataGranularity={props.xaxis.dataGranularity}
       
              />
            }
          />
          
        This is how my current xAxis looks . As soon as I add tickCount , Xaxis starts failing to render . I am not able to figure out why is that happening :(

**Comment by anshika1422** [comment]
Also if in increase the tickCount to 1000 and try to highlight and zoom , the xaxis is not updating and it stays in initial state. 
here : https://codesandbox.io/s/highlight-zomm-line-chart-forked-2wt62g

**Comment by anshika1422** [comment]
Hi all , Any updates would be helpful as its a major blocker in our implementation, Any workaround would also work. Thanks!!

**Comment by anshika1422** [comment]
Hi Guys, any timeline by when this issues could be fixed ?

**Comment by ckifer** [comment]
Any ideas on workarounds @nikolasrieble @HHongSeungWoo?

**Comment by nikolasrieble** [comment]
Did you try setting the ticks directly? 

<img width="1456" alt="Screenshot 2023-11-10 at 09 59 26" src="https://github.com/recharts/recharts/assets/27995606/7ed1306e-eba5-42d4-b07a-0b8d2d0f62ca">

**Comment by HHongSeungWoo** [comment]
I'm curious whether you want to remove ticks that go outside the grid or if you want all ticks to render and be properly rerendered during zoom in and zoom out.

**Comment by HHongSeungWoo** [comment]
First, we need to modify `getTicks`. The condition for rendering the last tick of the yAxis is causing the last tick of the xAxis to always render

**Comment by anshika1422** [comment]
> I'm curious whether you want to remove ticks that go outside the grid or if you want all ticks to render and be properly rerendered during zoom in and zoom out.

I want to remove the ticks that are outside the grid . When I highlight and zoom only those ticks should be visible on the X axis

**Comment by anshika1422** [comment]
> First, we need to modify `getTicks`. The condition for rendering the last tick of the yAxis is causing the last tick of the xAxis to always render

Hi , could u please help me with an example of the suggested solution in this code sandbox https://codesandbox.io/s/highlight-zomm-line-chart-forked-rph74z?file=/src/App.tsx in

**Comment by anshika1422** [comment]
> Did you try setting the ticks directly?
> 
> <img alt="Screenshot 2023-11-10 at 09 59 26" width="1456" src="https://user-images.githubusercontent.com/27995606/282009915-7ed1306e-eba5-42d4-b07a-0b8d2d0f62ca.png">
> Also, `linear` is not the right choice to show all ticks, but instead you should use the interval setting. Please have a look at https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-cartesian-cartesian-axis-tick-positioning--tick-positioning

1) If i am giving interval as 0  with type of xaxis as number even then all the ticks aren't showing .
(<XAxis interval={0} allowDataOverflow dataKey="name" domain={[left, right]} type="number" />)

If i remove the type as number and then give interval as 0 then atleast all the ticks are showing but then the drag and zoom functionality stops working.
(<XAxis interval={0} allowDataOverflow dataKey="name" domain={[left, right]}/>)

You can try the above mentioned issue in this example as well just change the Xaxis values
https://recharts.org/en-US/examples/HighlightAndZoomLineChart

**Comment by anshika1422** [comment]
Hi team , any updates on this ?

**Comment by anshika1422** [comment]
Hi Team , Any update on this bug ?

**Comment by anshika1422** [comment]
Hi 
I  tried to upgrade to beta version in sandbox and test , facing the same issue . I also upgraded the react version 
sandbox link --https://codesandbox.io/p/sandbox/highlight-zomm-line-chart-forked-y4syr9
If you see the below the attached image , when we  drag and zoom the x axis is still overflowing. 
What could be a possible solution for this?? As this bug is blocking a customer feature release for us 

<img width="694" alt="Image" src="https://github.com/user-attachments/assets/78d09811-0779-42a1-b82c-28e2cd7181f8" />

**Comment by ckifer** [comment]
We'll try to look into it in 3.x

CC @PavelVanecek

**Comment by anshika1422** [comment]
Is there a timeline by which we could expect this resolution ?

**Comment by ckifer** [comment]
No, this is an open source project not backed by anyone except individuals in spare time. If you need something in a particular time frame feel free to contribute and we will review and get your change through if it makes sense to do so.

**Comment by ckifer** [comment]
My workaround above stands as my solution. 

I would remove `scale="linear"` and then add `interval="equidistantPreserveStart"` and `tickCount={1000}`

It no longer stays in "initial state" like it did in 2.x

**Comment by anshika1422** [comment]
> 
> I would remove `scale="linear"` and then add `interval="equidistantPreserveStart"` and `tickCount={1000}`
> 
> It no longer stays in "initial state" like it did in 2.x

the problem for us here is we cannot skip the ticks on x axis and we need to show all the ticks . interval="equidistantPreserveStart"`. if we use this , the ticks are skipped based on the availble screen size

**Comment by gom59** [comment]
FYI I was facing the same issue in one of my charts. My dataset is never huge, so, as silly as it may sound, I ended up filtering the data being displayed, so only the current display range data is present in the dataset I feed my chart. I implemented horizontal scrolling outside recharts (just moving the filtered data window). This means you have to deal with some aspects yourself (like y scaling, so the charts doesn't change scale when you scroll around), but it's pretty simple to do, and works well.
This solves all the issues (I was having other problems, also with points out of range being displayed, not only ticks, weird left and right margins etc). I was content with recharts' rendering (compared to other libs) and with my other unaffected charts, so I stuck to it, and it's pretty solid this way.
This is an open source project, so you get what others are willing to put into this project for free :-)  (thanks to the contributors!)

**Comment by PavelVanecek** [comment]
Can't reproduce this on 3.2.1:

https://codesandbox.io/p/sandbox/highlight-zomm-line-chart-forked-tj2n75?file=%2Fsrc%2FApp.tsx%3A159%2C28

<img width="790" height="417" alt="Image" src="https://github.com/user-attachments/assets/391d0ba8-4bb9-4daf-837f-aaa732d319f8" />

https://codesandbox.io/p/sandbox/highlight-zomm-line-chart-forked-r2pkxx?file=%2Fsrc%2FApp.tsx

<img width="802" height="412" alt="Image" src="https://github.com/user-attachments/assets/ada64402-87ad-4f34-b80f-1dc1c3f29780" />

Are we good to close this? Or am I missing some edge case?

**Comment by ckifer** [comment]
Sounds like we can close it. Someone can comment back if they can still reproduce
