### ISSUE TITLE
Support React 19

### ISSUE THREAD

**Issue by justinh00k** [recharts/recharts#4558]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Charts do not render when using React 19, or when using NextJS 14.3 (which uses React 19).

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).
Install react@rc or react@beta
Observe charts do not render
https://github.com/justinh00k/recharts-react19-repro

## What is the expected behavior?
Charts render

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
2.12.7 / No

**Comment by ckifer** [comment]
React 19 will be added to peerDependencies when recharts supports it. 

Please see https://github.com/recharts/recharts/pull/4542 and https://github.com/recharts/recharts/issues/3615

**Comment by ckifer** [comment]
Going to edit the title if you don't mind to just "Support React 19", and use this to track support in 2.x

**Comment by ckifer** [comment]
Alpha release - https://www.npmjs.com/package/recharts/v/2.13.0-alpha.0
This BREAKS things in R19, shouldn't in R18

use this to determine what is breaking/what isn't. I just don't have bandwidth to fix it myself


Things that I know are broken:

Bar
Legend
Cursor
Pie

**Comment by ckifer** [comment]
https://www.npmjs.com/package/recharts/v/2.13.0-alpha.1
Should have more R19 support if not all of it (minus the need to disregard peerDeps and install react-is@19)

Please test this one as well on all React versions 16.8-19 to see if anyone runs into issues. Thanks! 🚀

**Comment by ckifer** [comment]
In order to use React 19 one must override the `react-is` version. This will always be true in 2.x. 3.x we will add react-is to peerDeps or remove it entirely
```
  "overrides": {
    "react-is": "^19.0.0-beta-26f2496093-20240514"
  }
```

**Comment by rauchg** [comment]
appreciate your work @ckifer

**Comment by ckifer** [comment]
Appreciate next helping out a bit here @rauchg !

**Comment by juliusmarminge** [comment]
Just tried on Next.js RC (React 19.0.0-rc-f994737d14-20240522) and my beautiful charts are back. Thank you 🙏

**Comment by rauchg** [comment]
My only issue remaining is `<Legend />` started rendering incorrectly, but it might be skill issue. I'm using Tremor, so maybe it's related to their impl and the version bump.

**Comment by ckifer** [comment]
@juliusmarminge Not sure why the types broke, are there React 19 types released? I can't seem to reproduce.

Also noticed that @rauchg - I think probably another defaultProps issue that hasn't been caught yet. Will take another look

**Comment by ckifer** [comment]
* [This](https://github.com/recharts/recharts/blob/master/src/component/Legend.tsx#L67) still uses defaultProps incorrectly (doesn't include them)
* [This](https://github.com/recharts/recharts/blob/master/src/util/getLegendProps.ts#L63) also causes issues (props not combined)

**Comment by eps1lon** [comment]
You definitely need to force `react-is@rc` either via `resolutions` (Yarn) or `overrides` (PNPM, NPM). 

`react-is` will be a peer dependency in 3.x to fix these issues (see https://github.com/recharts/recharts/pull/4541). But it's a breaking change so it can't land in 2.x.

**Comment by ckifer** [comment]
https://www.npmjs.com/package/recharts/v/2.13.0-alpha.3

Alpha-3 should fix the Legend issues mentioned above. Please continue to report other issues as you run into them, thanks!

**Comment by tobiaslins** [comment]
It seems like there is an issue with stacked bars. The same `stackId` does not stack but are overlapping
<img width="476" alt="image" src="https://github.com/recharts/recharts/assets/2978876/4255d22a-aa5f-4924-96ff-512a6452b384">

```
"next": "15.0.0-rc.0",
"react": "19.0.0-rc-6f23540c7d-20240528",
"react-dom": "19.0.0-rc-6f23540c7d-20240528",
"react-is": "19.0.0-rc-6f23540c7d-20240528",
"recharts": "2.13.0-alpha.3"
```

```tsx
   <Bar dataKey="pv" stackId="testing" fill="#8884d8" />
   <Bar dataKey="uv" stackId="testing" fill="#82ca9d" />
```

**Comment by ckifer** [comment]
Thanks @tobiaslins will look into it

**Comment by ckifer** [comment]
@tobiaslins I can reproduce here https://codesandbox.io/p/sandbox/stacked-bar-chart-7fwfgj
But I can't reproduce in the recharts repo and I'm not sure why. Makes debugging these issues difficult - if anyone wants to help feel free

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/blob/fad4d30c10186c4d5b97b0c87ed143a3d443c101/src/util/ChartUtils.ts#L1064

This is why stacks fail - we expect an axisId to be present but it isn't getting defaulted because of the way defaulProps change. This one doesn't seem as reasonable to refactor as the other ones so for now specifying axisIds on you graphical items and axes should fix it

**Comment by ckifer** [comment]
https://www.npmjs.com/package/recharts/v/2.13.0-alpha.4
Alpha 4 fixes the ReferenceLine typing issue and fixes stacked Bar and Area charts. 

@tobiaslins should be good to go now

**Comment by bel7aG** [comment]
`2.13.0-alpha.4` not rendering on the last react "rc" + last `next` canary "15.0.0-canary.77"

**Comment by abdullah-hallaq** [comment]
Same

**Comment by JRebertt** [comment]
@ckifer do you have any solution for this?

**Comment by ckifer** [comment]
I'm out this week, will take a look when I get back

**Comment by ckifer** [comment]
@bel7aG @abdullah-hallaq @JRebertt Is this a problem only with next or with the R19 version in vanilla react as well?

**Comment by ckifer** [comment]
Vanilla react seems to be working fine on the latest react RC
https://codesandbox.io/p/sandbox/stacked-bar-chart-forked-t3x3xv

If next broke something in their canary release it is up to them to fix it. If someone could make a reproduction repo using next that would be great, but I don't have capacity to do that at the moment

**Comment by JRebertt** [comment]
@ckifer If you try to use the new chart components from Shadcnui in Next.js 15rc with React 19, the charts don’t work

**Comment by ckifer** [comment]
I'm going to need more than that - I don't use Next and recharts does not explicitly guarantee support for specific frameworks. Recharts components are supposed to be used on the client. 

Does anyone know what changed in the recent canary releases?

**Comment by ckifer** [comment]
https://github.com/shadcn-ui/ui/blob/main/apps/www/package.json#L79

Shadcn UI uses recharts 2.12.7 so you'll need to make sure to override the recharts version to the latest alpha

**Comment by ckifer** [comment]
I created an empty next @ canary project, added recharts @ alpha and everything works fine at next canary.91. `use client` required

**Comment by JRebertt** [comment]
Really, I don't know what the problem is, because my chart lines are not appearing.



![CleanShot 2024-07-30 at 07 55 16@2x](https://github.com/user-attachments/assets/43e033b4-e3fb-4dfa-a7ff-0519329d8015)


`'use client'

import { TrendingUp } from 'lucide-react'
import { CartesianGrid, Line, LineChart, XAxis } from 'recharts'

import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  ChartConfig,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from '@/components/ui/chart'
const chartData = [
  { month: 'January', desktop: 186 },
  { month: 'February', desktop: 305 },
  { month: 'March', desktop: 237 },
  { month: 'April', desktop: 73 },
  { month: 'May', desktop: 209 },
  { month: 'June', desktop: 214 },
]

const chartConfig = {
  desktop: {
    label: 'Desktop',
    color: 'hsl(var(--chart-1))',
  },
} satisfies ChartConfig

export function Component() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Line Chart</CardTitle>
        <CardDescription>January - June 2024</CardDescription>
      </CardHeader>
      <CardContent>
        <ChartContainer config={chartConfig}>
          <LineChart
            accessibilityLayer
            data={chartData}
            margin={{
              left: 12,
              right: 12,
            }}
          >
            <CartesianGrid vertical={false} />
            <XAxis
              dataKey="month"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={(value) => value.slice(0, 3)}
            />
            <ChartTooltip
              cursor={false}
              content={<ChartTooltipContent hideLabel />}
            />
            <Line
              dataKey="desktop"
              type="natural"
              stroke="var(--color-desktop)"
              strokeWidth={2}
              dot={false}
            />
          </LineChart>
        </ChartContainer>
      </CardContent>
      <CardFooter className="flex-col items-start gap-2 text-sm">
        <div className="flex gap-2 font-medium leading-none">
          Trending up by 5.2% this month <TrendingUp className="h-4 w-4" />
        </div>
        <div className="leading-none text-muted-foreground">
          Showing total visitors for the last 6 months
        </div>
      </CardFooter>
    </Card>
  )
}
`

![CleanShot 2024-07-30 at 07 56 16@2x](https://github.com/user-attachments/assets/317b0c02-aaac-41a7-9fb9-e7ae1780750d)

**Comment by JRebertt** [comment]
@ckifer I use the use client directive in my chart component.

[https://gist.github.com/JRebertt/f54f9e07a8eb0674fcc186cac5b0fc87](url)

**Comment by JRebertt** [comment]
The same application using Next.js 14 and React 18 is working perfectly.

![CleanShot 2024-07-30 at 08 05 57@2x](https://github.com/user-attachments/assets/02a9cfee-db86-404d-ae2e-bcc2a1edc946)
![CleanShot 2024-07-30 at 08 07 46@2x](https://github.com/user-attachments/assets/6ea4afb8-d9ed-4bac-9676-30be12952529)

**Comment by ckifer** [comment]
@JRebertt make sure you are doing this 

https://github.com/recharts/recharts/issues/4558#issuecomment-2135604065

You upgraded to React 19 so you'll need to take the steps to make React 19 work. React Is needs to be forced to the latest canary version.

**Comment by JRebertt** [comment]
@ckifer What version should I use?

<img width="1473" alt="image" src="https://github.com/user-attachments/assets/6d3d1b2c-cb67-4906-91a6-35a345345767">

**Comment by ckifer** [comment]
Match it to your react version. So the 19-rc

**Comment by JRebertt** [comment]
@ckifer The problem persists even after installing

![CleanShot 2024-07-30 at 11 09 36@2x](https://github.com/user-attachments/assets/eb2427c1-a857-40da-a53c-32795d10a610)
![image](https://github.com/user-attachments/assets/225c8acc-85e5-477c-af69-2e98579b3f43)

**Comment by ckifer** [comment]
The react-is version needs to match the react version you are using. Copy the rc version string exactly including the hash starting in f994

**Comment by JRebertt** [comment]
@ckifer Dude, I deleted my lock file and the node_modules folder, and installed exactly the same version, but the error persists. Do you want to take a look at my repository?

![CleanShot 2024-07-30 at 11 17 30@2x](https://github.com/user-attachments/assets/51ed6957-f467-450b-bbbc-c17381c97af3)

**Comment by ckifer** [comment]
Sure I can take a look

**Comment by JRebertt** [comment]
@ckifer here https://github.com/JRebertt/fleet-fix-nextjs/tree/main

**Comment by ckifer** [comment]
everything working as expected
<img width="608" alt="image" src="https://github.com/user-attachments/assets/b7d07187-0016-43c9-b3c4-fcddde846f1a">

I just added an example chart, I can't use yours because auth is in the way/I don't have the API url

**Comment by JRebertt** [comment]
@ckifer Thank you very much, my friend, you are incredible.

![image](https://github.com/user-attachments/assets/e44bd771-e074-44e3-ab24-f1f05834b88b)

**Comment by neslob** [comment]
> for pnpm use https://pnpm.io/package_json#pnpmoverrides rather than overrides

Thanks, adding the following works great!

```json
  ...
  "dependencies": {
    ...
    "react": "19.0.0-rc-a7d1240c-20240731",
    "react-is": "19.0.0-rc-a7d1240c-20240731",
    "recharts": "2.13.0-alpha.4",
    ...
  },
  "pnpm": {
    "overrides": {
      "react-is": "$react-is"
    }
  },
```

**Comment by Gammon-parko** [comment]
`"dependencies": {
    "react": "^19.0.0-rc-fb9a90fa48-20240614",
    "react-dom": "^19.0.0-rc-fb9a90fa48-20240614",
    "react-is": "^19.0.0-rc-fb9a90fa48-20240614",
    "recharts": "^2.13.0-alpha.4",
  },
 "bun": {
    "overrides": {
      "react-is": "$react-is"
    }
  }
`
Can I use `bun` instead of `npm` or `pnpm`? The chart still does not render.

**Comment by ckifer** [comment]
I don't know how bun works but you should be able to sure

**Comment by Gammon-parko** [comment]
> ```
> "dependencies": {
>     "react": "^19.0.0-rc-fb9a90fa48-20240614",
>     "react-dom": "^19.0.0-rc-fb9a90fa48-20240614",
>     "react-is": "^19.0.0-rc-fb9a90fa48-20240614",
>     "recharts": "^2.13.0-alpha.4"
>   },
>   "bun": {
>     "overrides": {
>       "react-is": "$react-is"
>     }
>   }
> ```
> 
> Can I use `bun` instead of `npm` or `pnpm`? The chart still does not render.

I just switched to` pnpm` for testing, but the chart still isn’t rendering.

**Comment by ckifer** [comment]
Try deleting node modules and regenerating your lock file

**Comment by Gammon-parko** [comment]
> Try deleting node modules and regenerating your lock file

Fixed, I forgot to override the `recharts` as I am using `shadcn`.
Thx.

**Comment by PhucHuuDang** [comment]
i also have the issue that i'm using bun, so can i use this to override?: 

 "bun": {
    "overrides": {
      "react-is": "$react-is"
    }
  }

**Comment by ckifer** [comment]
You should not need to wrap anything in the "bun" key

https://bun.sh/docs/install/overrides#overrides

I haven't used bun but looking at the docs, you should be able to use regular NPM overrides
```
"overrides": {
"react-is": "$react-is"
}
```

**Comment by PhucHuuDang** [comment]
<img width="1387" alt="Screen Shot 2024-08-27 at 01 07 37" src="https://github.com/user-attachments/assets/cbdd341e-8d0d-49ad-8837-374d9d71d42e">

yah!, I got it, thanks for your supports a lot!! now it really coo!!

**Comment by PhucHuuDang** [comment]
if anyone uses bun, just adjust:

`
"overrides": {
"react-is": "$react-is"
}
`
and run "bun install"

**Comment by colinskow** [comment]
I was using a PNPM workspace and had to add the override (shown above) to the root `package.json`.

**Comment by absolutegravitas** [comment]
Doesnt work for me with the below package.json -- produces "PieChart cannot be used as a JSX component" error.  Yes,  I know about tsconfig jsx prop, no I can't change that for my current codebase.

![image](https://github.com/user-attachments/assets/77ad31b2-bbed-41ec-bf50-aaf85f3129b5)

![image](https://github.com/user-attachments/assets/b0681ea9-5d49-4887-9a18-3d669f8918cb)


`dependencies: {
...
    "react": "19.0.0-rc-4f604941-20240830",
    "react-dom": "19.0.0-rc-4f604941-20240830",
    "react-is": "19.0.0-rc-4f604941-20240830",
    "recharts": "2.13.0-alpha.4",
...}`

and 
` "overrides": {
    "@types/react": "npm:types-react@19.0.0-rc.0",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.0",
    "recharts": {
      "react-is": "$react-is"
    }
  }`

**Comment by ckifer** [comment]
So it goes with alpha/beta versions of things. I can't add react 19 as an accepted peerDep until R19 is released and adding react-is as a peerDep is a breaking change. 2.x will always be a little wonky but 3.0 should bring things back to normal.

**Comment by absolutegravitas** [comment]
Spoke too soon -- pnpm dev seems fine and renders charts but build fails with `PieChart cannot be used as a JSX component` (sigh)...

![image](https://github.com/user-attachments/assets/7f1646a1-2117-4b16-99c5-1676a0c16a17)

**Comment by ckifer** [comment]
@absolutegravitas does this happen for any chart or just Pie? I didn't know R19 versions of `@types/react` were out, changes there are probably what is causing this

**Comment by absolutegravitas** [comment]
Yeah any chart -- im using shadcn recharts on payloadcms template. Am happy to wait on a long term fix if you have other priorities. 

Payload requires rolling R19 rc versions to work it's bits and I've found an actual fix with ignore it using  ` {/* @ts-ignore */}` above the <PieChart> -- this let's me pass `pnpm dev` and `pnpm build`

![image](https://github.com/user-attachments/assets/09e88deb-2b5e-4b4d-96e3-da270f77a68b)

**Comment by ckifer** [comment]
Imho no one should be depending on recharts to "work in builds" with R19 until R19 is stable, but I guess that is risk that is knowingly taken on. 

Anyways, I confirmed this is fixed. I'll have to release another alpha version. Will post here when I can get to it

**Comment by ckifer** [comment]
New alpha version released https://www.npmjs.com/package/recharts/v/2.13.0-alpha.5
Type issue should be fixed, but please let me know if it isn't

**Comment by ChrisRoland** [comment]
Can I use recharts bar chart component in my NextJS.14 app?

**Comment by ckifer** [comment]
Yes

**Comment by arno-fukuda** [comment]
For folks using bun and still running into issues:
* Make sure you are on bun `>=1.0.6` for [overrides](https://bun.sh/blog/bun-v1.0.6) to work.

**Comment by GetPsyched** [comment]
Seems like it's fixed for the others yet I'm still having this issue. Relevant versions from my package.json:
```json
  "dependencies": {
    "next": "15.0.1",
    "react": "19.0.0-rc-69d4b800-20241021",
    "react-dom": "19.0.0-rc-69d4b800-20241021",
    "recharts": "^2.13.0",
  },
  "devDependencies": {
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1",
  },
  "overrides": {
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
  }
```

**Comment by ckifer** [comment]
@GetPsyched Your overrides are not correct. Override your "react-is" version to match your react version.

**Comment by GetPsyched** [comment]
Thanks for the extremely quick response! And it worked like a charm! Thanks.

**Comment by abdulsalamcodes** [comment]
> New alpha version released https://www.npmjs.com/package/recharts/v/2.13.0-alpha.5 Type issue should be fixed, but please let me know if it isn't

Please how did you achieve the 

> Thanks for the extremely quick response! And it worked like a charm! Thanks.

@GetPsyched please how did you achieve this. thanks.

**Comment by GetPsyched** [comment]
> @GetPsyched please how did you achieve this. thanks.

I added an override for the `react-is` package as well, just like the other overrides in my little code snippet above.

**Comment by ckifer** [comment]
React 19 is now stable - https://react.dev/blog/2024/12/05/react-19

Will look at an update when I can

**Comment by reintroducing** [comment]
@ckifer thanks for making the update to allow React 19 in the peerDeps. is it possible to get a build out with that update? This is the last dependency that's not allowing us to update to React 19 without forcing legacy peer deps.

**Comment by ckifer** [comment]
@reintroducing ack but currently on a trip for work. I make a new release when I get a few minutes or once I get home tomorrow

Thanks for understanding

**Comment by reintroducing** [comment]
@ckifer appreciate the quick reply, thank you very much.

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/releases/tag/v2.15.0

Released update to peerDeps in 2.15

You will still need to make sure react-is is correctly overridden!

Going to close this!

**Comment by reintroducing** [comment]
@ckifer works as expected as far as I can tell, thank you for the quick turn around on this, much appreciated.

**Comment by kossolax** [comment]
Still has a warning because of this submodule: https://github.com/recharts/react-smooth/issues/106

**Comment by ckifer** [comment]
Ok will update that this week

**Comment by ckifer** [comment]
Done in 4.0.4^

**Comment by uigywnkiub** [comment]
> In order to use React 19 one must override the `react-is` version. This will always be true in 2.x. 3.x we will add react-is to peerDeps or remove it entirely
> 
> ```
>   "overrides": {
>     "react-is": "^19.0.0-beta-26f2496093-20240514"
>   }
> ```

What is the latest ? or it is the latest react-is...

**Comment by ckifer** [comment]
It must match your react and react-dom version

So today

```json
"react": "19.0.0",
"react-dom": "19.0.0",
```
...
```json
"overrides": {
    "react-is": "19.0.0"
 }
 ```

**Comment by uigywnkiub** [comment]
> It must match your react and react-dom version
> 
> So today
> 
> ```json
> "react": "19.0.0",
> "react-dom": "19.0.0",
> ```
> 
> ...
> 
> ```json
> "overrides": {
>     "react-is": "19.0.0"
>  }
> ```

Thanks a lot!

**Comment by alicestoneprod** [comment]
v2.15.0 + react-is + react-v19 is perfectly works with WinCairo (WebKit – 605.1.11) - too much legacy browser without supporting of gap in flex. 
Thank you~
