### ISSUE TITLE
Stale dataKey value used when props change

### ISSUE THREAD

**Issue by RyanMcDonald** [recharts/recharts#4935]
## Do you want to request a feature or report a bug?

Bug.

## What is the current behavior?

If the `data` and `dataKey` props change, the **old** `dataKey` prop for each child `dataKey` ends up being called on new data, potentially causing errors.

This happens because [`getTooltipData` is called using `prevState` and the **new** data](https://github.com/recharts/recharts/blob/v2.13.0-alpha.4/src/chart/generateCategoricalChart.tsx#L1297). `prevState` has all of the out-of-date `graphicalItems`, so it will be calling the **previous** dataKey for each item.

We should be calling `getTooltipData` on the new state, including the updated `graphicalItems`.

## Demo

https://codesandbox.io/p/sandbox/recharts-stale-datakey-bug-9q4gtw?file=%2Fsrc%2FApp.tsx

## What is the expected behavior?

We should not attempt to use previous `dataKey` values on new data.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Tested on the latest 2.13.0-alpha.4 as well as 2.12.7.

**Comment by ckifer** [comment]
We're getting rid of the generator in 3.0 so this will definitely be fixed then. It probably won't be addressed in 2.x unless someone wants to contribute

**Comment by ckifer** [comment]
actually, I can't reproduce any issue in your sandbox. Aside from adding optional chaining to prevent undefined access, everything works as I would expect

**Comment by RyanMcDonald** [comment]
>actually, I can't reproduce any issue in your sandbox. Aside from adding optional chaining to prevent undefined access, everything works as I would expect

Having to add optional chaining is the issue here, though. I should be confident that `dataKey` is only being called on the data that I passed in, without having to add checks/guards.

**Comment by ckifer** [comment]
ack, agreed. 

Like I mentioned, this will go away in 3.0 and for now there is a way to work around it.
Majority I think use strings as their dataKeys rather than functions so that also cuts down the number affected by this.

Labeled to be fixed/confirmed as fixed in 3.x

**Comment by RyanMcDonald** [comment]
>Majority I think use strings as their dataKeys rather than functions so that also cuts down the number affected by this.

It's still an issue with strings as keys because the dataKey result would still be returning the wrong data (undefined), but I'm not sure what exactly the impacts of that would be in the rest of the code.

>Labeled to be fixed/confirmed as fixed in 3.x

Sounds good, thank you!

**Comment by ckifer** [comment]
this is oddly still a bug in 3.x alpha https://codesandbox.io/p/sandbox/recharts-stale-datakey-bug-forked-v2h28w
adding to bugs

**Comment by PavelVanecek** [comment]
This is interesting because now the dataKey is stale not because we call it with stale data but because Recharts now dispatches multiple actions on re-render because that's how Redux works and React renders on every of these actions because that's how React works and the chart state is inconsistent at some point - because the axes get removed during the render. This all happens in a single tick so it doesn't actually appear on the screen at any point but it does call the callback with undefineds.

I will figure something out.
