### ISSUE TITLE
Legend overlapping when data from server

### ISSUE THREAD

**Issue by YangZhouChaoFan** [recharts/recharts#511]
![image](https://cloud.githubusercontent.com/assets/13232941/22818398/febd13ce-efa7-11e6-9a11-0e3bce3e0f99.png)

It occurs at the first time when I get data from server side.
But when I get data from server side again, the line chart is right.

How can I make it right at the first time when I get data from server side.

**Comment by YangZhouChaoFan** [comment]
this is my code:

```
class SearchContentChart extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {

    const loadLines = data => data.map((item) => {
      return <Line type="monotone" key={item.key} dataKey={item.key} name={item.name} stroke={item.color} dot={null}/>
    });

    return (
      <ResponsiveContainer height={ 300 }>
        <LineChart data={this.props.data.data || []}>
          <XAxis dataKey="name"/>
          <YAxis />
          <CartesianGrid strokeDasharray="3 3"/>
          <Tooltip />
          <Legend/>
          {loadLines(this.props.data.line || [])}
        </LineChart>
      </ResponsiveContainer>
    )
  }
}
```

**Comment by xile611** [comment]
@YangZhouChaoFan How about the version of recharts? Can you create a jsfiddle demo to reproduce your problem ?

**Comment by YangZhouChaoFan** [comment]
@xile611 "recharts": "^0.20.2"，能方便邮件或者其他方式联系下吗？

**Comment by xile611** [comment]
@YangZhouChaoFan OK! I'll send email to you.

**Comment by elnygren** [comment]
I've seen this same issue manifest in my code. The issue is that the *first* render with actual data does not take into account the space occupied by legend but the *second* render (with actual data) does.

So basically after the first render, the chart has a bit too much height but it gets readjusted when rendering new data, for example. (I have a chart that dynamically loads new stuff from server after pressing a button)

**Comment by KyleAsaff** [comment]
@ctoppel I am having the same issue

**Comment by pratyushoak** [comment]
I see the same issue, where it resizes to the correct size after a while(maybe after some event).

**Comment by jojonjef** [comment]
same issue

**Comment by einomi** [comment]
I solved this issue by simply returning `null` if there is no data or if data's length equals to zero.

**Comment by Bhargav-Narayan** [comment]
Please help. I'm facing the same issue. Legend and chart overlaps initially. When hover over the chart, It resizes and displays both chart and legend properly.

**Comment by Pocket-titan** [comment]
Using a `ResponsiveContainer` and setting the `width` and `height` props on there instead of directly on the chart solves the issue for me.

Example:
```javascript
import {
    BarChart,
    Bar,
    CartesianGrid,
    ResponsiveContainer,
    XAxis,
    YAxis,
    Tooltip,
    Legend,
} from 'recharts'

const Chart = ({ data }) => (
  <ResponsiveContainer width={800} height={400}>
      <BarChart data={data}>
         <CartesianGrid stroke="#ccc" strokeDasharray="3 3" />
         <XAxis dataKey="x_key" />
	 <YAxis />
         <Tooltip />
         <Bar
           dataKey="y_key"
	   fill="#f3b448"
	   stroke="#694506"
	 />
	 <Legend />
      </BarChart>
  </ResponsiveContainer>
)
```

**Comment by Mohsen-Malekan** [comment]
same issue here, any update on this?

**Comment by KirillYoYo** [comment]
+1. What about responsive Legend? I try to use 'position relative' with adaptive height on 'recharts-legend-wrapper' - but then Legend stay below graph and flex-order doesn't work

**Comment by stevenheffner** [comment]
Having this issue as well! The legend overlaps itself, but fixes it self with the widow is resized or another button is clicked.

**Comment by VictoriaGribkova** [comment]
I have the same issue with area chart.

**Comment by raph90** [comment]
Same issue here.

**Comment by raph90** [comment]
Here's a potential fix: When your component loads, use an effect to do a state update. This will trigger an immediate re-render and everything should work: 

`
const [loaded, setLoaded] = useState(false)
  useEffect(() => {
    setTimeout(() => {
      setLoaded(true)
    }, 0)
    
  },[])
`

Then do {loaded && (chart goes here) }

**Comment by clarsen23** [comment]
I solved this issue by passing the graph some dummy data while the query was still loading: 
```
let data = []; 
if(loading){
    data = [
        { name: 'Remaining', value: 0},
        { name: 'Completed', value: 1}
      ];
} else {
    data = queryData
}
```
It is not perfect, as the data "flashes" from dummy to live data, but it resolved the overlapping issue for me

**Comment by Yeshwanthi** [comment]
Also this worked for me. Setting the legend wrapper style property. I am using recharts version 2.0.6.
`wrapperStyle={{ position: 'relative' }}`

**Comment by olelivalife** [comment]
> position: 'relative'

Setting `position: 'relative'` pushes legend below chart even though I have `verticalAlign: 'top'`

How do you keep Legend on top of chart with position: relative?

I think my problem was that I was conditionally rendering the Legend if there were data or not. I changed that to instead control display css property in wrapperStyle like this:

```
<Legend
            verticalAlign="top"
            align="right"
            wrapperStyle={{
              left: 0,
              top: 0,
              paddingBottom: 10,
              display: Object.keys(legendKeys).length ? 'block' : 'hidden',
            }}
            iconType="circle"
            iconSize={10}
            content={
              <ChartLegend
                translations={translations}
                chartConfig={config}
                legendKeys={legendKeys}
              />
            }
          />
          ```

**Comment by JakeRuth** [comment]
For people with complicated graphs that have changing # of graph lines after initial render, and who have also spent hours reading endless questions/different fixed for css hacks for this issue, here is a solution that is very hacky but really helped me after dealing with this bug for weeks.

https://github.com/recharts/recharts/issues/172#issuecomment-873633726

Hopefully the maintainers recognize this is a bug, that is my goal. This is a bug, and it should be fixed, assuming we want to fix bugs.

**Comment by peyman1992** [comment]
hello 
still overlaping legend with chart

**Comment by Lueton** [comment]
Same issue on 2.1.5. Could we at least reopen the issue?

**Comment by tayloryoung25** [comment]
Why are issues that are not resolved being closed? This is still a problem.

**Comment by kbeeveer46** [comment]
This is happening to me, as well. I have 3 line charts on the page. When the page loads some of them will be fine but the chart on some of them will use 100% of the page and completely cover my custom legend on the left. If I load new data from the server the charts will sometimes fix themselves. I also have a drop down to switch between chart types and when I chose a different option in the drop down and then go back to my line charts they all fix themselves. I've tried 100 different CSS and chart margin settings and can't figure out how to fix it.

**Comment by sutrik** [comment]
In my particular case the overlapping issue got fixed by adding debounce={1} to the ResponsiveContainer.
Perhaps the chart resizes itself too quickly before it can take the Legend into account.

**Comment by anpct** [comment]
Setting debounce={1} worked for me

**Comment by abidali671** [comment]
``

**Comment by JeongtaekLim** [comment]
<ResponsiveContainer debounce={1}> its also worked for me 2

**Comment by bsplosion** [comment]
> Setting debounce={1} to the ResponsiveContainer worked for me

Whoa.  That not only fixed this issue but a variety of other issues I was having related to responsive container rendering.  I wonder... is it possible that the insertion of the `Legend` is being handled by the `resize` event handler?  Are there other critical layout functions hooked to `resize`?

With the default of `debounce={0}` there might be a race condition where the resize fires and completes before the initial render, causing it to display the initial render variant without the child components resized accordingly.  This hypothesis is supported by observation of occasional flashes of the correct layout followed by the incorrect layout, and once in a while the correct layout is applied without fixes.

**Comment by ShuhaoBai** [comment]
Setting debounce={1} to the ResponsiveContainer didn't work for me, using v2.1.4. Also tried many other methods mentioned above, none of those fixed this issue. Anyone is experiencing the same issue?

**Comment by mhs-mlkn** [comment]
@ShuhaoBai I could only handle this problem by forcing my component to re-render

**Comment by JFWebb** [comment]
@ShuhaoBai I'm also still running into this issue-- none of the solutions mentioned here seem to work!

**Comment by JFWebb** [comment]
Update! After digging around in dev tools I realized that the auto-calculated heights of recharts-wrapper and recharts-surface were greater than the height of the responsive container. Adding the following to my css resolved the legend overlap issue for me by forcing each of those child divs to stay smaller than their parent divs.

`.recharts-wrapper {
  height: 99% !important;
}

.recharts-surface {
  height: 99% !important;
}`

**No** additional wrapperStyles or debounces need to be added to the Legend component for this. It should quickly resolve the issue for all charts on the page!

**Comment by benjamin-lindenbauer** [comment]
For me the issue was caused by a condition in the return statement. After removing it, everything worked as expected.

```
    return (
        sum > 0 && //remove this
        <ResponsiveContainer width='100%' height={64}>
```

**Comment by EP-PCOM** [comment]
Despite trying to implement every potential solution above, I'm still having this issue on initial render. I'm using the latest version (2.12.7) and am copying the sample code and data exactly as it is provided.
<img width="549" alt="Screen Shot 2024-09-11 at 1 13 05 PM" src="https://github.com/user-attachments/assets/8e1f766f-96c2-4ee9-9543-f0c422be4cb8">

**Comment by ckifer** [comment]
@EP-PCOM can you make a reproduction?

**Comment by ErwinKuipersNL** [comment]
None of the solutions above worked for me, what did work was setting `wrapperStyle={{ position: 'relative' }}` on `<Legend>`.
