### ISSUE TITLE
ComposedChart doesn't work in ResponsiveContainer with React 19 (in production)

### ISSUE THREAD

**Issue by lauri865** [recharts/recharts#5173]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Composed chart doesn't resize down within responsive container with React 19.0.0-rc-0bc30748-20241028

In development:
<img width="1350" alt="Screenshot 2024-10-29 at 21 14 34" src="https://github.com/user-attachments/assets/a7240e40-dcc0-468e-ace6-a974327c0dff">

In production (built with the latest version of Vite, incl. React Compiler, but disabling the compiler had no effect):
<img width="774" alt="Screenshot 2024-10-29 at 21 16 28" src="https://github.com/user-attachments/assets/06da5811-dd76-4d30-8274-dcf18bb98e17">

It works perectly fine in development, but in production, the ComposedChart displayName evaluates to "Component" as opposed to "CategoricalChart" in development. Hence the isChart check evaluates to false in ResponsiveContainer, and only width is set, as opposed to max-width.

## What is the expected behavior?
ResponsiveContainer works with ComposedChart

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
2.13.0 (latest)

**Comment by ckifer** [comment]
Please read the release notes https://github.com/recharts/recharts/releases/tag/v2.13.0


> R19 beta/RC releases can be used with Recharts under the following conditions:

>    Your react-is version matches your react and react-dom versions: use your package manager's override functionality to match your react-is version to your react version or else recharts elements will not show - see https://github.com/recharts/recharts/issues/4558#issuecomment-2135604065

**Comment by ckifer** [comment]
> ComposedChart displayName evaluates to "Component" as opposed to "CategoricalChart" in development. Hence the isChart check evaluates to false in ResponsiveContainer, and only width is set, as opposed to max-width.

If we can reproduce this particularly I can look into it, otherwise it should just be the usual react-is issue

**Comment by lauri865** [comment]
@ckifer, I'm doing that (and triple-checked based on other issue before posting).

From my pnpm-lock file:
react: 19.0.0-rc-0bc30748-20241028
react-dom: 19.0.0-rc-0bc30748-20241028(react@19.0.0-rc-0bc30748-20241028)
react-is: 19.0.0-rc-0bc30748-20241028

I will try to do a repro, but difficult to do it in CodeSandbox as it requires a build step.

**Comment by ckifer** [comment]
thank you for checking the other issues 🙏🏼 

Does starting with this help?

https://codesandbox.io/p/sandbox/stacked-bar-chart-forked-t3x3xv

**Comment by ckifer** [comment]
Interesting, I think I was able to reproduce in that sandbox

**Comment by ckifer** [comment]
Ok sorry @lauri865 I think the issue in the codesandbox is just a cache problem. I was able to get everything working normally in a local project with ComposedChart

**Comment by ckifer** [comment]
Full relevant package.json

```
  "dependencies": {
    "react": "19.0.0-rc-0bc30748-20241028",
    "react-dom": "19.0.0-rc-0bc30748-20241028",
    "react-is": "19.0.0-rc-0bc30748-20241028",
    "recharts": "^2.13.0"
  },
  "devDependencies": {
    "@types/react": "npm:types-react@rc",
    "@types/react-dom": "npm:types-react-dom@rc",
  },
  "overrides": {
    "react-is": "$react-is",
    "@types/react": "npm:types-react@rc",
    "@types/react-dom": "npm:types-react-dom@rc"
  }
```

**Comment by lauri865** [comment]
But the top chart doesn't even show up? Tried locally as well, and the same.

I think I might understand what's happening here though.

Here's a repro showing that ComposedChart doesn't have a displayName:
https://codesandbox.io/p/sandbox/stacked-bar-chart-forked-rhqcvq

`getDisplayName` gets the name also from children.type.name (root cause of the issue):
https://github.com/recharts/recharts/blob/ee9d9b0331a449ea0118e36dbc573218f94282f0/src/util/ReactUtils.ts#L53C1-L61C3

If you build it, the Component.name gets either minified or doesn't exist at all:
<img width="216" alt="Screenshot 2024-10-29 at 22 49 42" src="https://github.com/user-attachments/assets/144ca2a0-5b5c-444e-b586-5826a1b6b8ae">

Which explains why it worked for us in development, but not in production.

**Comment by ckifer** [comment]
https://codesandbox.io/p/devbox/8jmnj2?embed=1&file=%2Fsrc%2FApp.tsx

Fixed it, it turns out that that codesandbox uses pnpm so I converted it to a devbox, fixed overrides as per the pnpm spec and its working now.

**Comment by ckifer** [comment]
I'll try to fix the repro you gave

**Comment by ckifer** [comment]
https://codesandbox.io/p/devbox/wm7wry

Same issue, it looks like your `react-is` version is not being overridden correctly

**Comment by lauri865** [comment]
I don't follow. How does `react-is` affect the presence of `displayName`? It doesn't mutate the children, it only checks if it's a valid element or not. We have invoked getDisplayName manually in production without react-is in the loop, the problem remains.

The repro is still valid with the latest Codesandbox:
https://k2zwq5-5173.csb.app/

**Comment by lauri865** [comment]
And just to reiterate the core issue is not whether it renders or not (it does), but whether it is responsive or not in the Responsive container (yes in dev, no in prod).

**Comment by ckifer** [comment]
I think we're on two different issues here.

1. `react-is` needs overridden in order to work with React 19. This is why converting to a devbox and fixing overrides allows the chart to now render correctly in the linked sandboxes.
2. `displayName` has changed from 2.12 to 2.13 for all components that go through the categorical chart generator. See [this sandbox](https://codesandbox.io/p/sandbox/simple-bar-chart-forked-r75zxk?file=%2Fsrc%2FApp.tsx%3A76%2C13&workspaceId=7a1754d3-b261-47b1-9339-2aca93020961) on React 17 and 2.12 for confirmation of that (displayNames show correctly).

My question is why does issue 2 effect you in a negative way if the chart renders? Are you depending on displayName for something

**Comment by lauri865** [comment]
I never had a problem with the 1st point - it only ever existed in the first Codesandbox you provided. We're running the chart in prod.

The 2nd one I tried to explain in the issue. But to boil it down.
1. There's no displayName in prod
2. ResponsiveContainer's `isCharts` check fails
3. ResponsiveContainer sets parent container width to the chart (instead of maxWidth as it should)
4. The chart can only ever size up because of that
5. = it's not responsive

**Comment by ckifer** [comment]
I pulled down the sandbox, built, and served - the chart is responsive as expected
![image](https://github.com/user-attachments/assets/cb4c56f4-8006-47b7-a53e-901466ad6e7a)

**Comment by ckifer** [comment]
I'm not sure why responsiveness is working but I did get your logs to work correctly and return `false` for `isCharts`.
```
false Component
```

I'll dive deeper. Thanks for the persistence

**Comment by lauri865** [comment]
Sure, it works in a simplistic case where parentContainerWidth = ChartWidth.
But e.g. in a responsive columns based flexbox layout this breaks apart. If parent container grows to fit the children, and one child has a fixed width, the chart can't scale down anymore.

You can easily verify that the responsiveness doesn't work as intended by the implementation by verifying that the responsive container has a fixed width, and no maxWidth (as it should).

**Comment by ckifer** [comment]
Why would it be different in production... wild

**Comment by lauri865** [comment]
I explained that part above. `Component.name` is not a valid way to assess child component type, and is not the same as displayName. It's at the mercy of the build process / minifier what it becomes in the end, hence it only works in dev. I've made that mistake myself before.

**Comment by ckifer** [comment]
Oh totally agree, this is legacy from the original creators of recharts which we are slowly unraveling in the 3.x branch. They should have never reached into react internals to do anything, let alone determine what should be rendered and what should not. But here we are.

I think I found a workaround for the 2.x branch. We will remove react-is and these checks for 3.0 and this all should go away.

**Comment by lauri865** [comment]
Yea, I didn't understand why these checks exist in the first place. What are they protecting developers from? Not much if anything. We're already running a custom ResponsiveContainer in prod without these unnecessary checks.

**Comment by ckifer** [comment]
I don't either my friend, I don't either. I wanted to maintain non-breaking parity but I might just remove them now. Definitely not worth the pain

**Comment by ckifer** [comment]
I'll release 2.13.1 shortly

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/releases/tag/v2.13.1

Just waiting for https://github.com/recharts/recharts/actions/runs/11584060465 to finish

**Comment by ckifer** [comment]
Going to close this, thanks for the report and the help with figuring the issue out. Lmk if there are any issues
