### ISSUE TITLE
recharts 3.6.0: "Cannot assign to read only property 'lanes' of object '#<FiberNode>'" with React 19

### ISSUE THREAD

**Issue by CarlosZiegler** [recharts/recharts#6781]
## What is the current behavior?
When using recharts 3.6.0 with React 19.2.3, the application throws multiple TypeErrors related to React's internal fiber properties being read-only. The errors occur during chart rendering, particularly when ResponsiveContainer triggers resize-based state updates.

Error Messages: 
- Uncaught TypeError: Cannot assign to read only property 'lanes' of object '#<FiberNode>'
- Uncaught TypeError: Cannot assign to read only property 'pendingLanes' of object '#<FiberRootNode>'
- Uncaught TypeError: Cannot assign to read only property 'callbackNode' of object '#<FiberRootNode>'

Screenshots or videos are welcome.

<img width="1058" height="871" alt="Image" src="https://github.com/user-attachments/assets/04cb017c-ffa9-4ce0-acc9-3bbc91c954fa" />

<img width="1059" height="718" alt="Image" src="https://github.com/user-attachments/assets/751537da-2f97-4184-901d-54c3503f3e56" />

## What is the expected behavior?

Charts should render without errors on React 19.

Screenshots or videos are welcome.

## Please provide a demo of the problem in a sandbox

Here is how: https://github.com/recharts/recharts/wiki/How-to-share-a-demo

Please try to keep the demo as small as possible while still showing the problem.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

recharts version: 3.6.0
React version: 19.2.3
react-dom version: 19.2.3
Bundler: Vite (rolldown-vite)
Browser: Chrome

Related Issues
#5461 - react-redux versioning concerns with React 19
#5173 - ComposedChart in ResponsiveContainer issues with React 19
#5701 - Dependency management discussion for React 19 support

**Comment by ckifer** [comment]
cc @PavelVanecek 

@CarlosZiegler we haven't really anything outside the bounds of normal React so not sure why this would happen.

@PavelVanecek is this your Array changes?

**Comment by ckifer** [comment]
I can't reproduce with a new rolldown-vite project. @CarlosZiegler any more details you can give about your project?

**Comment by CarlosZiegler** [comment]
Hey, I will check more deeply tomorrow, if I can reproduce it on other project that I can share with you. Thanks for fast answer :)

**Comment by PavelVanecek** [comment]
No I don't think it's related, my array changes should be in dev only and don't make it to production.

Our own website is running on React 19 I think, and we have multiple integration tests on React 19 on top of that.

@CarlosZiegler if you can please share a reproduction then we can look into it.

**Comment by CarlosZiegler** [comment]
Hey I am trying to reproduce that case but looks like work fien in other projects, I will check more deeply and go back if this is related of recharts ( looks like i have some incompatibility problem now  ). Always thanks for the support :) Feelfre to close that/.

**Comment by YannickVillaescusa** [comment]
Im having the same problem, using react 19.2.3 with Recharts 3.5.1 goes fine but upgrading to 3.6.0 stops working.

**Comment by PavelVanecek** [comment]
@YannickVillaescusa can you share a reproduction please? Demo project or stackblitz link

**Comment by stheine** [comment]
We have the same issue, but in a big in-house application, so we cannot easily share this. For now we have reverted to 3.5.1.

**Comment by ckifer** [comment]
We've tried to reproduce but cannot. Can anyone give more details on your setup? All using Vite? 

Going to reopen just to keep track but we can't action until we can debug

**Comment by stheine** [comment]
I am using node 24.11.0, npm 11.6.4, webpack 5.100.1, webpack-dev-server 5.2.2
I have reproduced the issue, by changing recharts 3.5.1 to 3.6.0 in package.json and running npm install.

<img width="1186" height="706" alt="Image" src="https://github.com/user-attachments/assets/2bbaaf14-39c2-46db-89d4-68f9a6bc17dd" />


but now that I have spent some more time, trying to nail the issue, and I was removing node_modules and package-lock.json, the issue is not happening any more.
in another app, the situation is the same: just updating recharts in an existing node_modules install causes the issue, but when starting from a clean environment it doesn't.
I have a package-lock.json that causes the issue, but comparing to the new one from the clean environment shows so many diffs...

for me the issue is gone now, a fresh npm install in a clean environment helps (and yes, I should have tried that right away).
let's see if that helps for the others as well.

**Comment by YannickVillaescusa** [comment]
> I am using node 24.11.0, npm 11.6.4, webpack 5.100.1, webpack-dev-server 5.2.2 I have reproduced the issue, by changing recharts 3.5.1 to 3.6.0 in package.json and running npm install.
> 
> <img alt="Image" width="1186" height="706" src="https://private-user-images.githubusercontent.com/19614566/527434685-2bbaaf14-39c2-46db-89d4-68f9a6bc17dd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU5NjkxMTUsIm5iZiI6MTc2NTk2ODgxNSwicGF0aCI6Ii8xOTYxNDU2Ni81Mjc0MzQ2ODUtMmJiYWFmMTQtMzljMi00NmRiLTg5ZDQtNjhmOWE2YmMxN2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjE3VDEwNTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNmEwYmExZjcwNjU1MTZkMWZiZjhkODkyZjAwMDBjYjVjZTU2YWVlZWE1YTk1MWQ1YTM5ZWViMTM2YjlkNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UTrLBCfngRGc70S2S7DfuD9CVZdcDJKV5xACCvrNl8w">
> but now that I have spent some more time, trying to nail the issue, and I was removing node_modules and package-lock.json, the issue is not happening any more. in another app, the situation is the same: just updating recharts in an existing node_modules install causes the issue, but when starting from a clean environment it doesn't. I have a package-lock.json that causes the issue, but comparing to the new one from the clean environment shows so many diffs...
> 
> for me the issue is gone now, a fresh npm install in a clean environment helps (and yes, I should have tried that right away). let's see if that helps for the others as well.

I couldn't reproduce it either in a new project, and removing node_modules and package-lock.json solved it for me.

**Comment by philipbrembeck** [comment]
Can confirm that after removing the lock file (in my case bun.lock), and reinstalling, it works fine. Just removing node_modules did not help.
Maybe interesting: I've update via renovate before, there it did not work.

**Comment by chrystianmartins** [comment]
if you see https://github.com/recharts/recharts/blob/main/package.json, can see the version     "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0", to resolv, you can use tha same version in your project

**Comment by ckifer** [comment]
Is everyone here using npm? I cannot reproduce even after starting with 3.4 and upgrading progressively to 3.5, 3.5.1 and then 3.6.0.

This shouldn't have anything to do with our version of React types..

**Comment by ckifer** [comment]
If anyone could check their version of `immer` prior to the 3.6 upgrade that would be helpful. This could be caused by Redux toolkit upgrading immer to v11 from 10. 

So if your immer was previously 10 and is now 11 that might be it

I still can't reproduce with that assumption though

**Comment by CarlosZiegler** [comment]
In my case I can confirm after deleting lockfile and node_modules the project worked as expected. No issues form my side.

**Comment by coader** [comment]
I have deleted node_modules, but the issue still exists

**Comment by KevinArce98** [comment]
Same to @CarlosZiegler, I deleted lockfile and node_modules and it's working now

**Comment by romain-trotard** [comment]
Hello

I have been able to reproduce the problem [Reproduction](https://stackblitz.com/edit/xqymbgdu?file=package-lock.json,package.json&showSidebar=0&terminalHeight=10)

The problem comes from the version of `immer@11.0.0` which has a problem that has been fixed in [`11.0.1`](https://github.com/immerjs/immer/releases/tag/v11.0.1).  (This version is used by `@reduxjs/toolkit`)
Just upgrading the version to `11.0.1` or later worked for me.

**Comment by ckifer** [comment]
Nice @romain-trotard, thanks for finding that!

Since this is out of our control and there is a path forward I'm going to close this issue. 

For anyone who sees this later please make sure to resolve your immer version to anything 11.0.1 or above.

**Comment by iChaosren** [comment]
For anyone else still having this issue like me, add this to your `package.json`:
```json
  "resolutions": {
    "immer": "11.1.3"
  },
```

You can adjust the version, as long as it's above `11.0.1`, it should work

**Comment by martinbhans1** [comment]
> For anyone else still having this issue like me, add this to your `package.json`:
> 
>   "resolutions": {
>     "immer": "11.1.3"
>   },
> You can adjust the version, as long as it's above `11.0.1`, it should work

This issue has been bugging me for a full hour and none of the state-of-the-art models were able to figure this out for me, but your simple solution here solved it perfectly. You're proof forums are still much needed and beneficial. Thank you for taking the time to post this as it helps save other people tons of time debugging

**Comment by mohasinkr** [comment]
> For anyone else still having this issue like me, add this to your `package.json`:
> 
>   "resolutions": {
>     "immer": "11.1.3"
>   },
> 
> You can adjust the version, as long as it's above `11.0.1`, it should work

Thank you so much for sharing this, I am using mantine components which uses the recharts library under the hood.
